# Generated by Django 5.2.8 on 2026-10-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source_page', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='enquiry',
            name='contact_pref',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone call'), ('email', 'Email')], max_length=20, verbose_name='Best way to reach you'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='kind',
            field=models.CharField(choices=[('full', 'Full form'), ('quick', 'Quick form'), ('callback', 'Call back')], default='full', max_length=20),
        ),
    ]
